<a href="https://colab.research.google.com/github/thetsuthetsu/PythonSamples/blob/main/pytorch%E9%A0%86%E4%BC%9D%E6%90%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import torch.nn as nn

In [8]:
# 乱数のシードを固定
torch.manual_seed(0)

In [12]:
# torchバージョン確認
torch.__version__

'2.1.0+cu118'

In [9]:
# 3ノード -> 2ノードの全結合層 (fully-connected layer)
fc = nn.Linear(3,2)

In [10]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [11]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)

線形変換
- データ型をテンソル型に変える

In [13]:
x = torch.tensor([[1.,2.,3.]])

In [14]:
type(x), x.dtype

(torch.Tensor, torch.float32)

In [15]:
# 線形変換の計算
u = fc(x)

In [16]:
u

tensor([[-0.8219,  0.0526]], grad_fn=<AddmmBackward0>)

In [17]:
# 非線形変換の計算
import torch.nn.functional as F

In [18]:
# ReLU関数
# h = f(u) = max(0, u)
h = F.relu(u)

In [19]:
h

tensor([[0.0000, 0.0526]], grad_fn=<ReluBackward0>)

In [20]:
# 目的関数
# 目標値
t = torch.tensor([[1.], [3.]])
# 予測値
y = torch.tensor([[2.],[4.]])


In [21]:
# 平均二乗誤差の算出
F.mse_loss(y, t)

tensor(1.)